[build]
target = ["wasm32-unknown-unknown", "wasm32v1-none"]

[unstable]
# build-std = [] # "panic_abort", 

[profile.dev]
panic = "unwind"

[profile.release]
lto = true
opt-level = 3
panic = "abort"
