[build]
target = ["wasm32-unknown-unknown", "wasm32v1-none"]

[unstable]
# build-std = [] # "panic_abort", 

[profile.dev]
panic = "unwind"

[profile.release]
lto = true
opt-level = 3
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128,+bulk-memory,+sign-ext,+nontrapping-fptoint,+multivalue,+reference-types"]
