export const WIDTH = 256;
export const FILTER_COUNT = 2;
export const PACKED_SIZE = WIDTH * WIDTH;
export const PACKED_SIZE_FLOATS = PACKED_SIZE * 4;
export const PACKED_SIZE_BYTES =
    PACKED_SIZE_FLOATS * Float32Array.BYTES_PER_ELEMENT;
export const BUFFER_LENGTH_FLOATS = PACKED_SIZE_FLOATS * FILTER_COUNT;
export const BUFFER_LENGTH_BYTES =
    BUFFER_LENGTH_FLOATS * Float32Array.BYTES_PER_ELEMENT;
